# 1. Data

# Load data

Sample datasets:
    scikit-learn comes with a few standard datasets, for instance the iris and digits datasets for classification and the boston house prices dataset for regression.

In [ ]:

from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()
boston = datasets.load_boston()

## Digits

### Simple Exploratory Data Analysis (EDA)

Any dataset contains:
    - data: [n_samples, n_features]
    - target: [n_samples,]

In [ ]:
print(digits.data)
print(digits.data.shape)#(n_samples, n_features)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.imshow(digits.images[0])

### You could plot from data directly

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

plt.imshow(np.reshape(digits.data[0], [8, 8]))

In [ ]:
print(digits.target)
print(digits.target.shape)
print(digits.images.shape)


## Iris

### Simple Exploratory Data Analysis (EDA)

In [ ]:
dataset = iris
#print(dataset.data)
print(dataset.data.shape)#(n_samples, n_features)
#print(dataset.target)
print(dataset.target.shape)

## Boston

### Simple Exploratory Data Analysis (EDA)

In [ ]:
dataset = boston
#print(dataset.data)
print(dataset.data.shape)#(n_samples, n_features)
#print(dataset.target)
print(dataset.target.shape)

# Machine learning with sklearn

- Load and prepare data
- Model selection
- Model fitting
- Evaluation

# Simple Classification example

## Model = SVM

In [ ]:
In sklearn, we have:
    - SVC --> SVM Classifier
    - SVR --> SVM Regressor

In [ ]:
from sklearn import svm
model = svm.SVC(gamma=0.001, C=100.)

Fit ao all data except the last example--> keep for test

In [ ]:
model.fit(digits.data[:-1], digits.target[:-1])  


In [ ]:
model.predict(digits.data[-1:])

In [ ]:
plt.imshow(np.reshape(digits.data[-1:], [8, 8]))

# Model persistence (save/load)

## Using python only

Save using pickle

In [ ]:
import pickle
s = pickle.dumps(model)

Load using pickle

In [ ]:
model_loaded = pickle.loads(s)
print(model_loaded.predict(digits.data[-1:]))
plt.imshow(np.reshape(digits.data[-1:], [8, 8]))

Note that pickle has some security and maintainability issues. Please refer to section Model persistence (http://scikit-learn.org/stable/modules/model_persistence.html#model-persistence) for more detailed information about model persistence with scikit-learn.

## Using scikit learn

In the specific case of the scikit, it may be more interesting to use joblib’s replacement of pickle (joblib.dump & joblib.load), which is more efficient on big data, but can only pickle to the disk and not to a string

In [ ]:
from sklearn.externals import joblib
joblib.dump(model, 'model_joblib.pkl') 

In [ ]:
model_loaded_joblib = joblib.load('model_joblib.pkl') 
print(model_loaded_joblib.predict(digits.data[-1:]))
plt.imshow(np.reshape(digits.data[-1:], [8, 8]))

# Sklearn conventions

scikit-learn estimators follow certain rules to make their behavior more predictive.
Check: http://scikit-learn.org/stable/tutorial/basic/tutorial.html

## Unless otherwise specified, input will be cast to float64

In [ ]:
import numpy as np
from sklearn import random_projection

rng = np.random.RandomState(0)
X = rng.rand(10, 2000)
X = np.array(X, dtype='float32')
print('Input type is: ', X.dtype)


transformer = random_projection.GaussianRandomProjection()
X_new = transformer.fit_transform(X)
print('After sklearn fit_transform, the input is cast to float64', X_new.dtype)

### The above rule is applicable only to regression targets, not classification. Classification targets are mentained.

In [ ]:
from sklearn import datasets
from sklearn.svm import SVC
iris = datasets.load_iris()
clf = SVC()
clf.fit(iris.data, iris.target)  





list(clf.predict(iris.data[:3]))


clf.fit(iris.data, iris.target_names[iris.target])  





list(clf.predict(iris.data[:3]))  


## Re-fitting hyper params

Hyper-parameters of an estimator can be updated after it has been constructed via the sklearn.pipeline.Pipeline.set_params method. Calling fit() more than once will overwrite what was learned by any previous fit()

In [ ]:
import numpy as np
from sklearn.svm import SVC

rng = np.random.RandomState(0)
X = rng.rand(100, 10)
y = rng.binomial(1, 0.5, 100)
X_test = rng.rand(5, 10)


clf = SVC()
print('Initial SVC model constructed')

print('Override the kernel to linear')
clf.set_params(kernel='linear').fit(X, y)  




print(clf.predict(X_test))


print('Override the kernel to rbf')
clf.set_params(kernel='rbf').fit(X, y)  


print(clf.predict(X_test))

# Target labels encoders

All in sklearn.preprocessing

# Difference between ordinal and nominal
http://www.mymarketresearchmethods.com/types-of-data-nominal-ordinal-interval-ratio/

    
## Nominal: 

Nominal scales are used for labeling variables, without any quantitative value.  “Nominal” scales could simply be called “labels.”  Here are some examples, below.  Notice that all of these scales are mutually exclusive (no overlap) and none of them have any numerical significance.  A good way to remember all of this is that “nominal” sounds a lot like “name” and nominal scales are kind of like “names” or labels.
    
    
## Oridnal: 

With ordinal scales, it is the order of the values is what’s important and significant, but the differences between each one is not really known.  Take a look at the example below.  

In each case, we know that a #4 is better than a #3 or #2, but we don’t know–and cannot quantify–how much better it is.  

For example, is the difference between “OK” and “Unhappy” the same as the difference between “Very Happy” and “Happy?”  We can’t say.

Ordinal scales are typically measures of non-numeric concepts like satisfaction, happiness, discomfort, etc.

“Ordinal” is easy to remember because is sounds like “order” and that’s the key to remember with “ordinal scales”–it is the order that matters, but that’s all you really get from these.

## Categorial case (LableEncoder)

If the input is an array of strings, and we want to fit NOMINAL or ORDINAL (higher value is higher importance), we use LabelEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
print('Raw labels are: ', ["paris", "paris", "tokyo", "amsterdam"])

le.fit(["paris", "paris", "tokyo", "amsterdam"])

print('The available UNIQUE classes are: ', list(le.classes_))

print('The oridnal of ["tokyo", "tokyo", "paris"] is: ', le.transform(["tokyo", "tokyo", "paris"]) )

print('The inverse transofrm into strings of [2 2 1] is: ', list(le.inverse_transform([2, 2, 1])))

We may even have input categories as numbers, not as strings. 

We may want to give them ascending order "RANKs" (0,1,2,3...etc)

In [ ]:
print('Raw labels are: ', [1, 2, 2, 6])

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit([1, 2, 2, 6])

print('The available UNIQUE classes are: ', list(le.classes_))

print('The oridnal of [1, 1, 2, 6] is: ', le.transform([1, 1, 2, 6]) )

print('The inverse transofrm into strings of [0, 0, 1, 2] is: ', le.inverse_transform([0, 0, 1, 2]))

## Multiclass case on ordinal data (LabelBinarizer)

Many classifiers are binary, only produce 1 or 0. To transform it into multi-class case (n_classes), a common way is to use one-vs-all.

In this case, you n_classes classifiers, each is trained on 0/1 task. If the input instance belongs to a class, then its desired output is 1 and all others are zeros.

This mandates to encode the targets in a special way, also known as one-hot encoding

In [ ]:
from sklearn.svm import SVC
from sklearn.preprocessing import LabelBinarizer

X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]
y = [0, 0, 1, 1, 2]
print('Normally, the target is formatted as: ', y)

y = LabelBinarizer().fit_transform(y)
print('We can use the LabelBinarizer to perform the one-hot-encoding: \n', y)

## The one-hot-encoding is mandatory for the NN softmax for example.

## One-hot-encoder (OHE) on categorial data

First we transform to ordinal using LabelEncoder then use LabelBinarizer to get the OHE

In [ ]:
y_raw = [1, 2, 2, 6]
print('Raw labels are: ', y_raw)

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y_raw)

print('The available UNIQUE classes are: ', list(le.classes_))

y_ordinal = le.transform(y_raw)
print('The oridnal of [1, 1, 2, 6] is: ', y_ordinal )

print('The inverse transofrm into strings of [0, 0, 1, 2] is: ', le.inverse_transform(y_ordinal))

from sklearn.preprocessing import LabelBinarizer


y_OHE = LabelBinarizer().fit_transform(y_ordinal)
print('We can use the LabelBinarizer to perform the one-hot-encoding: \n', y_OHE)

## Multi-labels vs. Multi-Class

In some cases, we may need to assign more than one label for an instance/example.

This is encountered in case of multi-task learning.

Example: https://arxiv.org/abs/1612.07695
        
In this case, we can encode more than one position as 1 at a time.        

In [15]:
from sklearn.preprocessing import MultiLabelBinarizer
y = [[0, 1], [0, 2], [1, 3], [0, 2, 3], [2, 4]]
y = MultiLabelBinarizer().fit_transform(y)
print(y)


[[1 1 0 0 0]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [1 0 1 1 0]
 [0 0 1 0 1]]


# One vs ALL classifier

After formatting the target variables, how to fit a one vs. ALL classifier?

In [20]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer

X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]
y = [0, 0, 1, 1, 2]

y = LabelBinarizer().fit_transform(y)
classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X, y).predict(X)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

OneVsRestClassifier can also work on categorial y directly

In [18]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer

X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]
y = [0, 0, 1, 1, 2]

classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X, y).predict(X)

array([0, 0, 1, 1, 2])

# One hot encoding of the INPUT features (not targets)

Suppose we have a dataset (Design matrix X [n_samples, n_features].

And we have ALL or SOME of the features as categorial/ordinal.

For some classifiers like DecisionTrees, they work directly on ordinal/cat data. For others (NN or SVM), ordinal values mean more importance to some features than others.


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
print('Raw labels are: ', ["paris", "paris", "tokyo", "amsterdam"])

le.fit(["paris", "paris", "tokyo", "amsterdam"])

print('The available UNIQUE classes are: ', list(le.classes_))

print('The oridnal of ["tokyo", "tokyo", "paris", "amsterdam"] is: ', le.transform(["tokyo", "tokyo", "paris", "amsterdam"]) )


For SVM or NN, it means that tokyo is twice weighted as paris!

So we better encode cat/oridinal features as OHE


We cannot use as before, since LabelEncoder and Binarizer work on 1-D array of labels

In [ ]:
X_raw = [[1, 2, 2, 6], [1, 2, 2, 6], [1, 2, 2, 6]]
print('Raw data are: ', X_raw)

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(X_raw)



LabelEncoder works on labels only: 1-D. To make it work on matrix we must convert into pandas data frame first.

In [ ]:
X_raw = [[1, 2, 2, 6, 1], [1, 2, 2, 6, 1], [1, 2, 2, 6, 6]]
print('Raw data are: ', X_raw)
import pandas as pd
X = pd.DataFrame(X_raw)

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
X_ordinal = X.apply(le.fit_transform)

import numpy as np
#print('The oridnal values are: \n', np.array(X_ordinal))
print('The oridnal values are: \n', X_ordinal)

print('The inverse transofrm into strings of [0, 0, 1, 2] is: ', le.inverse_transform(X_ordinal))

from sklearn.preprocessing import LabelBinarizer


X_OHE = LabelBinarizer().fit_transform(X_ordinal)
print('We can use the LabelBinarizer to perform the one-hot-encoding: \n', X_OHE)

What happened? We see all features are assigned 0!!

This is because, pandas dataframe is created in colomns. The LabelEncoder scans each colomn independently!
So in each col we can see the same value.

In [ ]:
X

Now, let's see more appealing example (each feature has variations in colomns):

In [ ]:
import pandas as pd
import numpy as np

X_raw = [[1, 2, 2, 6, 1], [2, 8, 2, 2, 1], [4, 10, 2, 6, 6]]
print('Raw data are: ', X_raw)

X = pd.DataFrame(X_raw)
print(X)

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
#X_ordinal = X.apply(le.fit_transform)
le.fit_transform(X)
X_oridnal = le.transform(X)



The error above because we cannot fit a transform on X.

Instead we can only fit it on COLOMNS of X.

To do this, we use X.apply, which works per colomn:

In [ ]:
import pandas as pd
import numpy as np

X_raw = [[1, 2, 2, 6, 1], [2, 8, 2, 2, 1], [4, 10, 2, 6, 6]]
print('Raw data are: ', X_raw)

X = pd.DataFrame(X_raw)
print(X)

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
X_ordinal = X.apply(le.fit_transform)



#print('The oridnal values are: \n', np.array(X_ordinal))
print('The oridnal values are (pandas DF): \n', X_ordinal)
#print('The oridnal values are: \n', X_ordinal.toarray())

print('The inverse transofrm into strings of [0, 0, 1, 2] is: ', le.inverse_transform(X_ordinal))

from sklearn.preprocessing import LabelBinarizer


X_OHE = LabelBinarizer().fit_transform(X_ordinal)
print('We can use the LabelBinarizer to perform the one-hot-encoding: \n', X_OHE)

The error above means, since we do not fit a UNIVERSAL transform for X, but only per colomn, then we cannot apply inverse_transform globally.

What we need to do is to have a LabelEncoder transform object PER COLOMN/FEATURE

In [ ]:
import pandas as pd
import numpy as np

X_raw = [[1, 2, 2, 6, 1], [2, 8, 2, 2, 1], [4, 10, 2, 6, 6]]
print('Raw data are: ', X_raw)

X = pd.DataFrame(X_raw)

print('Before transform: \n', X)
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le_dict = {}
for col in X.columns:
    #print(col.name)
    #print(X[col].name)
    le = preprocessing.LabelEncoder()
    X[col] = le.fit_transform(X[col])
    le_dict[X[col].name] = le
    
print('After transform: \n', X)
for col in X.columns:
    
    X[col] = le_dict[X[col].name].inverse_transform(X[col])
    


print('After inverse transform: \n', X)

The same can be done with shorthand lambda expressions:

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

X_raw = [[1, 2, 2, 6, 1], [2, 8, 2, 2, 1], [4, 10, 2, 6, 6]]
print('Raw data are: ', X_raw)

X = pd.DataFrame(X_raw)

print('Before transform: \n', X)

from collections import defaultdict
le_dict = defaultdict(LabelEncoder)

# X.apply loops on colomns, so small x is the col
X = X.apply(lambda x: le_dict[x.name].fit_transform(x))
    
print('After transform: \n', X)

X = X.apply(lambda x: le_dict[x.name].inverse_transform(x))
    


print('After inverse transform: \n', X)

Now we can transform categorial features into ordinal ones, and inverse that.

Now, we want to fit a OHE.

Let's try with LabelBinarizer as before:

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

X_raw = [[1, 2, 2, 6, 1], [2, 8, 2, 2, 1], [4, 10, 2, 6, 6]]
print('Raw data are: ', X_raw)

X = pd.DataFrame(X_raw)

print('Before transform: \n', X)

from collections import defaultdict
le_dict = defaultdict(LabelEncoder)

# X.apply loops on colomns, so small x is the col
X_ordinal = X.apply(lambda x: le_dict[x.name].fit_transform(x))
    
print('After transform: \n', X_ordinal)

X_orig = X_ordinal.apply(lambda x: le_dict[x.name].inverse_transform(x))
    


print('After inverse transform: \n', X_orig)

from sklearn.preprocessing import LabelBinarizer

X_OHE = LabelBinarizer().fit_transform(X_ordinal)
print('We can use the LabelBinarizer to perform the one-hot-encoding: \n', X_OHE)

As before, LabelBinarize like LabelEncoder work only on 1-D labels array.

Let's try to work on the colomns data of X_ordinal as we did with LabelEncoder:

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

X_raw = [[1, 2, 2, 6, 1], [2, 8, 2, 2, 1], [4, 10, 2, 6, 6]]
print('Raw data are: ', X_raw)

X = pd.DataFrame(X_raw)

print('Before transform: \n', X)

from collections import defaultdict
le_dict = defaultdict(LabelEncoder)

# X.apply loops on colomns, so small x is the col
X_ordinal = X.apply(lambda x: le_dict[x.name].fit_transform(x))
    
print('After transform: \n', X_ordinal)

X_orig = X_ordinal.apply(lambda x: le_dict[x.name].inverse_transform(x))
    


print('After inverse transform: \n', X_orig)

from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()

X_OHE = X_ordinal.apply(lb.fit_transform)
print('We can use the LabelBinarizer to perform the one-hot-encoding: \n', X_OHE)

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

X_raw = [[1, 2, 2, 6, 1], [2, 8, 2, 2, 1], [4, 10, 2, 6, 6]]
print('Raw data are: ', X_raw)

X = pd.DataFrame(X_raw)

print('Before transform: \n', X)

from collections import defaultdict
le_dict = defaultdict(LabelEncoder)

# X.apply loops on colomns, so small x is the col
X_ordinal = X.apply(lambda x: le_dict[x.name].fit_transform(x))
    
print('After transform: \n', X_ordinal)

X_orig = X_ordinal.apply(lambda x: le_dict[x.name].inverse_transform(x))
    
print('After inverse transform: \n', X_orig)


from sklearn.preprocessing import LabelBinarizer

lb_dict = {}
X_OHE = pd.DataFrame()
for col in X_ordinal.columns:
    lb = LabelBinarizer()
    a = lb.fit_transform(X_ordinal[col])
    X_OHE[col] = a
    lb_dict[X_ordinal[col].name] = lb
    

print('We can use the LabelBinarizer to perform the one-hot-encoding: \n', X_OHE)

for col in X_OHE.columns:
    
    X_ordinal_orig[col] = lb_dict[X_OHE[col].name].inverse_transform(X_OHE[col])
print('After inverse transform: \n', X_ordinal_orig)

The error above is because we are trying to put 3 values (one hot encoding of 0--> 1,0,0) for each colomn.

### sklearn provides a ready make class for OHE on features:

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

X_raw = [[1, 2, 2, 6, 1], [2, 8, 2, 2, 1], [4, 10, 2, 6, 6]]
print('Raw data are: ', X_raw)

X = pd.DataFrame(X_raw)

print('Before transform: \n', X)

from collections import defaultdict
le_dict = defaultdict(LabelEncoder)

# X.apply loops on colomns, so small x is the col
X_ordinal = X.apply(lambda x: le_dict[x.name].fit_transform(x))
    
print('After transform: \n', X_ordinal)

X_orig = X_ordinal.apply(lambda x: le_dict[x.name].inverse_transform(x))
    
print('After inverse transform: \n', X_orig)




enc = preprocessing.OneHotEncoder()
X_OHE_ = enc.fit_transform(X_ordinal) 
X_OHE = X_OHE_.toarray()
print(X_OHE.shape)
print('The one-hot-encoding: \n', X_OHE)



### You don't even need to use LabelEncoder first!

In [8]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

X_raw = [[1, 2, 2, 6, 1], [2, 8, 2, 2, 1], [4, 10, 2, 6, 6]]
print('Raw data are: ', X_raw)



enc = preprocessing.OneHotEncoder()
X_OHE_ = enc.fit_transform(X_raw) 
X_OHE = X_OHE_.toarray()
print(X_OHE.shape)
print('The one-hot-encoding: \n', X_OHE)



Raw data are:  [[1, 2, 2, 6, 1], [2, 8, 2, 2, 1], [4, 10, 2, 6, 6]]
(3, 11)
The one-hot-encoding: 
 [[ 1.  0.  0.  1.  0.  0.  1.  0.  1.  1.  0.]
 [ 0.  1.  0.  0.  1.  0.  1.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  1.  1.  0.  1.  0.  1.]]


Note the shape is still 3 rows, but 11 colomns, since we 3 values for first and second feature/colomn, and only 2 (1 and 6) for the 3rd one.

The inverse is not possible:

In [9]:
X_orig_ordinal = enc.inverse_transform(X_OHE)

AttributeError: 'OneHotEncoder' object has no attribute 'inverse_transform'

## One hot encoding on categorial (names) data

In [7]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

X_raw = [["A", "D", "G", "A", "K"], ["B", "E", "H", "C", "L"], ["C", "F", "J", "B", "M"]]
print('Raw data are: ', X_raw)



enc = preprocessing.OneHotEncoder()
X_OHE_ = enc.fit_transform(X_raw) 
X_OHE = X_OHE_.toarray()
print(X_OHE.shape)
print('The one-hot-encoding: \n', X_OHE)



Raw data are:  [['A', 'D', 'G', 'A', 'K'], ['B', 'E', 'H', 'C', 'L'], ['C', 'F', 'J', 'B', 'M']]


ValueError: could not convert string to float: 'A'

It doesn't work without LabelEnbcoder first

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

X_raw = [["A", "D", "G", "A", "K"], ["B", "E", "H", "C", "L"], ["C", "F", "J", "B", "M"]]
print('Raw data are: ', X_raw)

X = pd.DataFrame(X_raw)

print('Before transform: \n', X)

from collections import defaultdict
le_dict = defaultdict(LabelEncoder)

# X.apply loops on colomns, so small x is the col
X_ordinal = X.apply(lambda x: le_dict[x.name].fit_transform(x))
    
print('After transform: \n', X_ordinal)

X_orig = X_ordinal.apply(lambda x: le_dict[x.name].inverse_transform(x))
    
print('After inverse transform: \n', X_orig)




enc = preprocessing.OneHotEncoder()
X_OHE = enc.fit_transform(X_ordinal).toarray()
print(X_OHE.shape)
print('The one-hot-encoding: \n', X_OHE)



### But we may use DictVictorizer

In [6]:

import pandas as pd
import numpy as np
from sklearn import preprocessing

X_raw = [["A", "D", "G", "A", "K"], ["B", "E", "H", "C", "L"], ["C", "F", "J", "B", "M"]]
print('Raw data are: ', X_raw)


X = pd.DataFrame(X_raw).to_dict( orient = 'records' )

from sklearn.feature_extraction import DictVectorizer
enc = DictVectorizer()
X_OHE = enc.fit_transform(X).toarray()
print(X_OHE.shape)
print('The one-hot-encoding: \n', X_OHE)

print(enc.inverse_transform(X_OHE))







Raw data are:  [['A', 'D', 'G', 'A', 'K'], ['B', 'E', 'H', 'C', 'L'], ['C', 'F', 'J', 'B', 'M']]
(3, 15)
The one-hot-encoding: 
 [[ 1.  0.  0.  1.  0.  0.  1.  0.  0.  1.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  1.  0.  0.  1.  0.  0.  0.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  1.  0.  0.  1.  0.  1.  0.  0.  0.  1.]]
[{'0=A': 1.0, '1=D': 1.0, '3=A': 1.0, '2=G': 1.0, '4=K': 1.0}, {'4=L': 1.0, '0=B': 1.0, '1=E': 1.0, '2=H': 1.0, '3=C': 1.0}, {'4=M': 1.0, '0=C': 1.0, '3=B': 1.0, '1=F': 1.0, '2=J': 1.0}]


Why it generates OHE directly?

http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.DictVectorizer.html#sklearn.feature_extraction.DictVectorizer
    
However, note that this transformer will only do a binary one-hot encoding when feature values are of type string. 

If categorical features are represented as numeric values such as int, the DictVectorizer can be followed by OneHotEncoder to complete binary one-hot encoding.

In [13]:
from sklearn.feature_extraction import DictVectorizer
v = DictVectorizer(sparse=False)
D = [{'foo': 1, 'bar': 2}, {'foo': 3, 'baz': 1}]
X = v.fit_transform(D)
print(X)


enc = preprocessing.OneHotEncoder()
X_OHE = enc.fit_transform(X).toarray()
print('The one-hot-encoding: \n', X_OHE)

[[ 2.  0.  1.]
 [ 0.  1.  3.]]
The one-hot-encoding: 
 [[ 0.  1.  1.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.  1.]]


# Estimator object

### Fitting data: the main API implemented by scikit-learn is that of the estimator. 

An estimator is any object that learns from data; it may be a classification, regression or clustering algorithm or a transformer that extracts/filters useful features from raw data.

All estimator objects expose a fit method that takes a dataset (usually a 2-d array) (n_samples, n_features):

### Estimator parameters: 
All the parameters of an estimator can be set when it is instantiated or by modifying the corresponding attribute:

# References
http://scikit-learn.org/stable/tutorial/basic/tutorial.html